### ISSUE TITLE
Finalisation Wireframe

### ISSUE THREAD

**Issue by BenOtsoa** [tifus69/projet_client_fictif1#7]
Julien, peux-tu finaliser les wireframes en intégrant les modifs dont nous avons parlé en réunion? Merci

**Comment by blomki** [comment]
Noté. Je fais ça ce soir. Je prends la relève de @tifus69 et @hkhkm.

**Comment by blomki** [comment]
Mis à jour en prenant en compte les remarques de cet apm.
